import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ReactFlow,Background,Controls,MiniMap,Node,Edge} from '@xyflow/react';
import {Activity,Archive,ArrowUpRight,BookOpen,Box,ChevronDown,ChevronRight,ClipboardCheck,Cloud,Code2,Database,FileKey2,Gauge,LayoutDashboard,LockKeyhole,Menu,MoreHorizontal,Play,Plus,RefreshCw,Search,Settings2,ShieldCheck,SlidersHorizontal,Users,X} from 'lucide-react';
import '@xyflow/react/dist/style.css';
import './styles.css';
import {login,request} from './api';
import {mapSecurityExecution,stages,ExecutionStep} from './flow/execution/mapSecurityExecution';

const edges:Edge[]=stages.slice(0,-1).map((_,i)=>({id:`e${i}`,source:`n${i}`,target:`n${i+1}`}));
const scenarios=['Owner Read','Viewer Mutation Denied','Cross-Tenant Resource 404','RLS Unscoped Query','Quota Exceeded','Feature Disabled'];
const probeFor=(label:string)=>label.includes('RLS')?'unscoped_query_under_rls':label.includes('Cross')?'cross_tenant_resource':label.includes('Viewer')?'viewer_mutation':label.includes('Quota')?'quota_exhaustion':label.includes('Owner')?'owner_read':'feature_gate_denial';
const nav=[['Overview',LayoutDashboard],['Security Explorer',ShieldCheck],['Projects',Box],['Tenants',Cloud],['Members',Users],['Audit trail',ClipboardCheck]] as const;
type Trace={status_code:number;outcome:string;steps:{name:string;state:string;metadata:Record<string,unknown>}[]};

function App(){
  const [email,setEmail]=useState('alice@demo.local'); const [token,setToken]=useState(''); const [tenant,setTenant]=useState('Acme Labs');
  const [sidebar,setSidebar]=useState(true); const [activeNav,setActiveNav]=useState('Security Explorer'); const [query,setQuery]=useState('');
  const [result,setResult]=useState('Choose a scenario to inspect its authorization path.'); const [projects,setProjects]=useState<string[]>([]);
  const [traceId,setTraceId]=useState(''); const [trace,setTrace]=useState<Trace|null>(null); const [drawer,setDrawer]=useState(false);
  const [steps,setSteps]=useState<ExecutionStep[]>(stages.map((name,i)=>({name,state:i===0?'running':'idle',detail:i===0?'Waiting for a scenario':'Waiting'})));
  const run=async(label:string)=>{try{const data=await request(`/api/security/probes/${probeFor(label)}`,{method:'POST'},token,tenant);setTraceId(data.trace_id??'');setSteps(mapSecurityExecution(label,data.evidence??{}));if(data.trace_id){const saved=await request(`/api/traces/${data.trace_id}`,{},token,tenant);setTrace(saved);}setDrawer(true);setResult(`${label} ${data.passed?'validated':'blocked'} by the backend boundary.`);}catch(error){setResult(`Backend unavailable: ${error instanceof Error?error.message:'request failed'}`);}};
  const replay=async()=>{if(!trace){setResult('Run a backend scenario before replaying it.');return;}for(let i=0;i<stages.length;i+=1){setSteps(current=>current.map((step,index)=>({...step,state:index<i?'succeeded':index===i?'running':'idle',detail:index<i?'Replayed from trace':index===i?'Replaying':'Waiting'})));await new Promise(resolve=>setTimeout(resolve,70));}setResult(`Replay complete for trace ${traceId.slice(0,12)}.`);};
  const doLogin=async()=>{try{const data=await login(email,'demo-password');setToken(data.access_token);const list=await request('/api/projects',{},data.access_token,tenant);setProjects(list.items.map((p:{name:string})=>p.name));setResult('Session authenticated · tenant context ready.');}catch(error){setResult(`Login failed: ${error instanceof Error?error.message:'request failed'}`);}};
  const createProject=async()=>{if(!token){setResult('Sign in before creating a project.');return;}try{const created=await request('/api/projects',{method:'POST',body:JSON.stringify({name:`Workspace ${projects.length+1}`,description:'Created from the tenant-scoped console',status:'active'})},token,tenant);setProjects(current=>[...current,created.name]);setResult(`${created.name} created inside ${tenant}.`);}catch(error){setResult(`Create denied: ${error instanceof Error?error.message:'request failed'}`);}};
  const nodes:Node[]=stages.map((name,i)=>({id:`n${i}`,position:{x:(i%5)*210,y:Math.floor(i/5)*125},data:{label:name,state:steps[i].state,detail:steps[i].detail},type:'default'}));
  const visible=scenarios.filter(x=>x.toLowerCase().includes(query.toLowerCase()));
  return <div className={`metronic-app ${sidebar?'sidebar-open':'sidebar-collapsed'}`}>
    <aside className="sidebar"><div className="brand"><span className="brand-mark"><ShieldCheck size={19}/></span><span>Sentinel<span className="brand-muted">.console</span></span></div><div className="sidebar-section-label">PLATFORM</div><nav>{nav.map(([label,Icon])=><button className={activeNav===label?'nav-item active':'nav-item'} onClick={()=>setActiveNav(label)} key={label}><Icon size={18}/><span>{label}</span>{label==='Security Explorer'&&<span className="nav-ping"/>}</button>)}</nav><div className="sidebar-section-label">WORKSPACE</div><button className="nav-item"><Settings2 size={18}/><span>Settings</span></button><div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><BookOpen size={16}/></div><b>Need help?</b><small>Read the security guide</small><button>Open documentation <ArrowUpRight size={13}/></button></div><div className="profile"><span className="avatar">{email[0].toUpperCase()}</span><div><b>{token?email.split('@')[0]:'Guest operator'}</b><small>{token?'Security team':'Sign in required'}</small></div><MoreHorizontal size={18}/></div></div></aside>
    <div className="page-shell"><header className="topbar"><button className="icon-button menu-button" onClick={()=>setSidebar(!sidebar)}><Menu size={20}/></button><div className="breadcrumb"><span>Workspace</span><ChevronRight size={14}/><b>{activeNav}</b></div><div className="topbar-actions"><div className="search"><Search size={16}/><input placeholder="Search workspace" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><button className="icon-button"><Activity size={18}/><i/></button><button className="icon-button"><Settings2 size={18}/></button><div className="top-profile"><span className="avatar small">{email[0].toUpperCase()}</span><ChevronDown size={14}/></div></div></header>
      <main className="content"><div className="page-heading"><div><div className="eyebrow">SECURITY OPERATIONS</div><h1>Security Explorer</h1><p>Understand every tenant boundary before it reaches production.</p></div><div className="heading-actions"><button className="btn btn-light"><Archive size={16}/> Export report</button><button className="btn btn-primary" onClick={()=>run('Owner Read')}><Play size={16} fill="currentColor"/> Run validation</button></div></div>
        <section className="context-bar"><div className="context-title"><span className="context-icon"><Cloud size={17}/></span><div><small>ACTIVE TENANT CONTEXT</small><b>{tenant}</b></div></div><div className="context-meta"><span className="plan-badge"><span/> Starter plan</span><span className="divider"/><span><LockKeyhole size={14}/> X-Tenant-ID scoped</span><select value={tenant} onChange={e=>setTenant(e.target.value)}><option>Acme Labs</option><option>Globex Cloud</option></select></div></section>
        <section className="kpi-grid"><Kpi icon={<ShieldCheck/>} tone="primary" label="Boundary checks" value="14" trend="All scenarios mapped"/><Kpi icon={<Gauge/>} tone="warning" label="Active projects" value={`${projects.length || 1} / 3`} trend="Starter quota"/><Kpi icon={<Database/>} tone="success" label="RLS status" value="Enforced" trend="Runtime role verified"/><Kpi icon={<Activity/>} tone="info" label="Last trace" value={traceId?traceId.slice(0,8):'—'} trend={trace?'Persisted evidence':'No trace selected'}/></section>
        <section className="explorer-grid"><div className="card scenario-card"><div className="card-header"><div><h2>Validation scenarios</h2><p>Run a controlled probe and inspect the exact decision path.</p></div><button className="icon-button"><SlidersHorizontal size={17}/></button></div><div className="scenario-list">{visible.map((label)=><button className="scenario-row" onClick={()=>run(label)} key={label}><span className={`scenario-icon ${label.includes('Denied')||label.includes('404')?'danger':'success'}`}>{label.includes('Denied')||label.includes('404')?<LockKeyhole size={15}/>:<ShieldCheck size={15}/>}</span><span className="scenario-name"><b>{label}</b><small>{label.includes('RLS')?'PostgreSQL policy enforcement':label.includes('Quota')?'Capacity gate and usage lock':'Authentication · tenant · RBAC'}</small></span><span className="scenario-state">{trace&&result.startsWith(label)?(trace.outcome==='allowed'?'verified':'blocked'):'ready'}</span><ChevronRight size={16}/></button>)}</div><div className="card-footer"><span><span className="live-dot"/> Demo mode enabled</span><button onClick={()=>setActiveNav('Audit trail')}>View audit trail <ArrowUpRight size={14}/></button></div></div>
          <div className="card trace-card"><div className="card-header"><div><h2>Execution trace</h2><p>{trace?`Trace ${traceId.slice(0,16)} · HTTP ${trace.status_code}`:'Live request path across trust boundaries'}</p></div><button className="btn btn-light btn-sm" onClick={replay}><RefreshCw size={14}/> Replay</button></div><div className="trace-canvas"><ReactFlow nodes={nodes} edges={edges} fitView panOnDrag><Background color="#e7edf5" gap={22}/><Controls/><MiniMap/></ReactFlow></div><div className="trace-legend"><span><i className="legend-dot success"/> allowed</span><span><i className="legend-dot danger"/> denied</span><span><i className="legend-dot neutral"/> not reached</span></div></div></section>
        <section className="bottom-grid"><div className="card"><div className="card-header"><div><h2>Tenant projects</h2><p>Resources visible in the current context.</p></div><button className="btn btn-primary btn-sm" onClick={createProject}><Plus size={15}/> New project</button></div><div className="table-wrap"><table><thead><tr><th>PROJECT</th><th>STATUS</th><th>ACCESS</th><th>OWNER</th><th/></tr></thead><tbody>{(projects.length?projects:['Acme Control Plane']).map((p,i)=><tr key={p}><td><span className="project-icon"><Code2 size={15}/></span><b>{p}</b></td><td><span className="status-pill active"><i/> Active</span></td><td><span className="access-pill"><LockKeyhole size={12}/> tenant-scoped</span></td><td>Alice Owner</td><td><button className="icon-button"><MoreHorizontal size={16}/></button></td></tr>)}</tbody></table></div></div><div className="card audit-card"><div className="card-header"><div><h2>Trace inspector</h2><p>Persisted decision evidence.</p></div><button className="icon-button" onClick={()=>setDrawer(!drawer)}>{drawer?<X size={17}/>:<ArrowUpRight size={17}/>}</button></div>{trace?<div className="inspector"><div className="inspector-result"><span className="result-icon"><ShieldCheck size={18}/></span><div><b>{trace.outcome==='allowed'?'Boundary passed':'Boundary blocked'}</b><small>Recorded by backend audit</small></div></div>{trace.steps.map((step,i)=><div className="inspector-step" key={`${step.name}-${i}`}><span className={`step-number ${step.state}`}>{String(i+1).padStart(2,'0')}</span><span><b>{step.name}</b><small>{step.state} · {JSON.stringify(step.metadata)}</small></span></div>)}</div>:<div className="empty-state"><span><FileKey2 size={22}/></span><b>No trace selected</b><small>Run a validation scenario to populate the inspector.</small></div>}</div></section>
      </main><footer><span>Sentinel.console v0.1.0</span><span><span className="live-dot"/> PostgreSQL runtime protected</span></footer></div>
    {drawer&&trace&&<div className="trace-drawer"><div className="drawer-header"><div><small>TRACE INSPECTOR</small><h2>{traceId}</h2></div><button className="icon-button" onClick={()=>setDrawer(false)}><X size={18}/></button></div><div className="drawer-status"><span className="result-icon"><ShieldCheck size={20}/></span><div><b>{trace.outcome}</b><small>HTTP {trace.status_code} · {trace.steps.length} recorded steps</small></div></div>{trace.steps.map((step,i)=><div className="drawer-step" key={i}><span className={`step-number ${step.state}`}>{i+1}</span><div><b>{step.name}</b><small>{step.state}</small><code>{JSON.stringify(step.metadata,null,2)}</code></div></div>)}</div>}
  </div>
}
function Kpi({icon,tone,label,value,trend}:{icon:React.ReactNode;tone:string;label:string;value:string;trend:string}){return <div className="card kpi"><span className={`kpi-icon ${tone}`}>{icon}</span><div><small>{label}</small><strong>{value}</strong><span className="kpi-trend"><ArrowUpRight size={13}/>{trend}</span></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
