import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ReactFlow,Background,Controls,MiniMap,Node,Edge} from '@xyflow/react';
import '@xyflow/react/dist/style.css'; import './styles.css'; import {login,request} from './api'; import {mapSecurityExecution,stages,ExecutionStep} from './flow/execution/mapSecurityExecution';
const edges:Edge[]=stages.slice(0,-1).map((_,i)=>({id:`e${i}`,source:`n${i}`,target:`n${i+1}`}));
function App(){const [email,setEmail]=useState('alice@demo.local');const [token,setToken]=useState('');const [tenant,setTenant]=useState('Acme Labs');const [result,setResult]=useState('Ready for a real backend request.');const [projects,setProjects]=useState<string[]>([]);const [traceId,setTraceId]=useState('');const [trace,setTrace]=useState<{status_code:number;outcome:string;steps:{name:string;state:string;metadata:Record<string,unknown>}[]}|null>(null);const [steps,setSteps]=useState<ExecutionStep[]>(stages.map((name,i)=>({name,state:i===0?'running':'idle',detail:i===0?'Select a scenario to execute':'Waiting'})));
const run=async(label:string)=>{try{const probe=label.includes('RLS')?'unscoped_query_under_rls':label.includes('Cross')?'cross_tenant_resource':label.includes('Viewer')?'viewer_mutation':label.includes('Quota')?'quota_exhaustion':label.includes('Owner')?'owner_read':'feature_gate_denial';const data=await request(`/api/security/probes/${probe}`,{method:'POST'},token,tenant);setTraceId(data.trace_id??'');setSteps(mapSecurityExecution(label,data.evidence??{}));if(data.trace_id){const saved=await request(`/api/traces/${data.trace_id}`,{},token,tenant);setTrace(saved);}setResult(`${label}: ${data.passed?'security boundary held':'request allowed'} · backend probe recorded`);}catch(error){setResult(`Backend unavailable: ${error instanceof Error?error.message:'request failed'}`);}};
const replay=async()=>{if(!trace){setResult('Run a backend scenario before replaying it.');return;}for(let i=0;i<stages.length;i+=1){setSteps(current=>current.map((step,index)=>({...step,state:index<i?'succeeded':index===i?'running':'idle',detail:index<i?'Replayed from persisted trace':index===i?'Replaying':'Waiting'})));await new Promise(resolve=>setTimeout(resolve,90));}setResult(`Replay complete · ${trace.outcome} · trace ${traceId.slice(0,8)}`);};
const nodes:Node[]=stages.map((name,i)=>({id:`n${i}`,position:{x:(i%5)*210,y:Math.floor(i/5)*135},data:{label:name,state:steps[i].state,detail:steps[i].detail},type:'default'}));
const doLogin=async()=>{try{const data=await login(email,'demo-password');setToken(data.access_token);const list=await request('/api/projects',{},data.access_token,tenant);setProjects(list.items.map((p:{name:string})=>p.name));setResult('Authenticated with Argon2-backed local JWT.');}catch(error){setResult(`Login failed: ${error instanceof Error?error.message:'request failed'}`);}};
const createProject=async()=>{if(!token){setResult('Sign in before creating a project.');return;}try{const name=`Workspace ${projects.length+1}`;const created=await request('/api/projects',{method:'POST',body:JSON.stringify({name,description:'Created from the tenant-scoped UI',status:'active'})},token,tenant);setProjects(current=>[...current,created.name]);setResult(`Created ${created.name} inside ${tenant}.`);}catch(error){setResult(`Create denied: ${error instanceof Error?error.message:'request failed'}`);}};
return <div className="app"><header><div><span className="eyebrow">SECURITY EXPLORER</span><h1>Multi-Tenant SaaS Platform</h1></div><div className="identity">{token?email+' · '+tenant:'Local demo · sign in required'}</div></header><main><aside><section className="panel"><h2>Demo users</h2><select value={email} onChange={e=>setEmail(e.target.value)}><option>alice@demo.local</option><option>vera@demo.local</option><option>sam@demo.local</option><option>carol@demo.local</option></select><button onClick={doLogin}>{token?'Authenticated':'Login · demo-password'}</button><h2>Tenant context</h2><select value={tenant} onChange={e=>setTenant(e.target.value)}><option>Acme Labs</option><option>Globex Cloud</option></select><p className="muted">X-Tenant-ID selects context; membership authorizes it.</p></section><section className="panel"><h2>Security lab</h2>{['Owner Read','Viewer Mutation Denied','Cross-Tenant Resource 404','RLS Unscoped Query','Quota Exceeded','Feature Disabled'].map(x=><button className="scenario" onClick={()=>run(x)} key={x}>{x}<span>→</span></button>)}</section></aside><div className="workspace"><div className="hero"><div><span className="eyebrow">LIVE REQUEST TRACE</span><h2>{result}</h2></div><div className="stat"><b>{projects.length} / 3</b><span>active projects · starter</span></div></div><div className="canvas"><ReactFlow nodes={nodes} edges={edges} fitView><Background color="#20304a" gap={22}/><Controls/><MiniMap/></ReactFlow></div><div className="bottom"><section className="panel"><h2>Projects</h2>{projects.map(p=><div className="project" key={p}><span className="dot"/> {p}<small>tenant-scoped</small></div>)}<button onClick={createProject}>＋ Create project</button></section><section className="panel"><h2>Trace timeline</h2><div className="timeline">{steps.filter(s=>s.state!=='idle').slice(0,8).map((s,i)=><div className={s.state} key={s.name}><b>0{i+1}.0 ms</b><span>{s.name}</span><small>{s.detail}</small></div>)}</div><button onClick={replay}>↻ Replay persisted trace</button>{trace&&<p className="muted">Trace {traceId.slice(0,12)} · HTTP {trace.status_code} · {trace.steps.length} persisted steps</p>}</section></div></div></main></div>}
createRoot(document.getElementById('root')!).render(<App/>);
